version: "3.0"

networks:
  transport-proxy:
    external: false

services:
  server:
    image: owlsoul/ytproxy:latest
    build:
      context: .
      dockerfile: Dockerfile.alpine
    restart: unless-stopped
    container_name: "ytproxy"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # set host's timezone
      - /etc/localtime:/etc/localtime:ro
      # or set arbitrary timezone
      #- /usr/share/zoneinfo/Europe/Samara:/etc/localtime:ro
    networks:
      - transport-proxy
    ports:
      - "25555:25555"
    command: ./transport_proxy.py --delay 10 --verbose 4
