#!/usr/bin/env python3

"""
Yandex Transport Monitor proxy service, automates getting data from Yandex.Transport using Selenium
"""

import time
import sys
import json
from YandexTransportCore import YandexTransportCore


class Application:
    """
    Main application class
    """
    def __init__(self):
        pass

    def run(self):
        """
        Run the application
        :return: exit code
        """

        core = YandexTransportCore()
        core.startWebdriver()

        # Getting stop info example
        res = core.getStopInfo(url="https://yandex.ru/maps/213/moscow/?"
                                   "ll=37.579537,C55.821644&"
                                   "masstransit[stopId]=stop__9639753&"
                                   "mode=stop&"
                                   "z=16")
        # Printing the output
        print(json.dumps(res, sort_keys=True, indent=4, separators=(',', ': ')))
        time.sleep(5)

        # Getting vehicles info example
        res = core.getVehiclesInfo(url="https://yandex.ru/maps/213/moscow/?"
                                       "ll=37.589633%2C55.835559&"
                                       "masstransit[routeId]=213_56_trolleybus_mosgortrans&"
                                       "masstransit[stopId]=stop__9639753&"
                                       "masstransit[threadId]=213A_56_trolleybus_mosgortrans&"
                                       "mode=stop&"
                                       "z=14")
        # Printing the output
        print(json.dumps(res, sort_keys=True, indent=4, separators=(',', ': ')))

        core.stopWebdriver()

# -------------------------------------------------------------------------------------------------------------------- #
if __name__ == '__main__':
    app = Application()
    app.run()
    sys.exit(0)
